version: '3.8'
services:
  flask-app:
    build: ./flask-app
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  fastapi-app:
    build: ./fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store_db
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: store_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  postgres_data:
